name: CI

on:
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
    build-test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: Install dependencies
          run: npm ci
          
        - name: Build the application
          run: npm run build
          
        - name: Run tests
          run: npm test
      